name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Checkout du code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Connexion à GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Étape 3 : Construction de l'image
    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/pid:latest .

    # Étape 4 : Push de l'image
    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/pid:latest
